### ISSUE TITLE
运行不了提示 Full authentication is required to access this resource

### ISSUE THREAD

**Issue by ejiyuan** [qzeng2490/Spring-Boot-JWT-OAuth2#1]
哥们 你好 我用 crul调用 
curl -X POST -vu client:secret http://localhost:9899/oauth/token -H "Accept: application/json" -d "password=1&username=qiang&grant_type=password&scope=read%20write&client_secret=XY7kmzoNzl100&client_id=testjwtclientid"
返回：
{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}

**Comment by qzeng2490** [comment]
你试试postman. 我的配置如下
<img width="980" alt="2018-04-12 11 13 57" src="https://user-images.githubusercontent.com/5402552/38654586-a662f960-3e42-11e8-8334-d386e074713c.png">

**Comment by ejiyuan** [comment]
嗯 不错 是crul 的问题！
能否支持sso？我添加login登录
